import { useEffect, useState } from 'react';
import { GitCompareArrows, LoaderCircle } from 'lucide-react';
import { compareAttempts, listAttempts, type AttemptComparison, type ExecutionAttemptSummary } from '../services/history';

function fmt(value: string | null | undefined) { return value ? new Date(value).toLocaleString() : '—'; }
function delta(value: number | null | undefined) { return value == null ? '—' : `${value > 0 ? '+' : ''}${value}`; }

export function ExecutionHistory({ id }: { id: number }) {
  const [attempts, setAttempts] = useState<ExecutionAttemptSummary[]>([]);
  const [before, setBefore] = useState(''); const [after, setAfter] = useState('');
  const [comparison, setComparison] = useState<AttemptComparison | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { setLoading(true); setError(''); setComparison(null); listAttempts(id).then(data => { setAttempts(data); if (data.length >= 2) { setBefore(data[1].execution_attempt_id); setAfter(data[0].execution_attempt_id); } else { setBefore(''); setAfter(''); } }).catch(e => setError(e instanceof Error ? e.message : 'Unable to load execution history')).finally(() => setLoading(false)); }, [id]);
  async function compare() { if (!before || !after || before === after) { setError('Select two different attempts from this investigation.'); return; } setError(''); try { setComparison(await compareAttempts(id, before, after)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to compare attempts'); } }
  if (loading) return <div className="glass rounded-2xl p-8 text-center text-sm text-zinc-500"><LoaderCircle className="mx-auto mb-3 animate-spin" size={22}/>Loading execution history…</div>;
  return <div className="space-y-5">
    {error && <div role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
    <div className="glass rounded-2xl p-5"><div className="font-medium">Execution History</div><div className="mt-1 text-xs text-zinc-500">Durable attempts remain separate. Historical evidence stays attached to its execution attempt.</div><div className="mt-4 space-y-2">{attempts.map(a => <div key={a.execution_attempt_id} className={`rounded-xl border p-4 ${a.current ? 'border-red-400/30 bg-red-500/[.04]' : 'border-white/7 bg-white/[.02]'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-medium">{a.current ? 'Current attempt' : 'Historical attempt'} <span className="font-mono text-xs text-zinc-500">{a.execution_attempt_id}</span></div><span className="text-xs uppercase tracking-wider text-zinc-500">{a.status} · {a.outcome}</span></div><div className="mt-2 grid gap-2 text-xs text-zinc-500 sm:grid-cols-3"><div>Started: {fmt(a.started_at)}</div><div>Finished: {fmt(a.finished_at)}</div><div>Recovered: {fmt(a.recovered_at)}</div></div>{a.recovery_reason && <div className="mt-2 text-xs text-zinc-600">Recovery: {a.recovery_reason}</div>}</div>)}</div>{attempts.length < 2 && <div className="mt-4 text-sm text-zinc-500">At least two attempts are required for comparison.</div>}</div>
    {attempts.length >= 2 && <div className="glass rounded-2xl p-5"><div className="flex items-center gap-2"><GitCompareArrows size={17} className="text-red-400"/><div><div className="font-medium">Compare Attempts</div><div className="text-xs text-zinc-500">Only attempts belonging to investigation #{id} can be selected.</div></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm"><span className="mb-2 block text-xs uppercase tracking-wider text-zinc-500">Attempt A · baseline</span><select aria-label="Baseline attempt" value={before} onChange={e => setBefore(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#101010] px-3 py-3">{attempts.map(a => <option key={a.execution_attempt_id} value={a.execution_attempt_id}>{a.execution_attempt_id.slice(0, 12)} · {a.status}</option>)}</select></label><label className="text-sm"><span className="mb-2 block text-xs uppercase tracking-wider text-zinc-500">Attempt B · later</span><select aria-label="Later attempt" value={after} onChange={e => setAfter(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#101010] px-3 py-3">{attempts.map(a => <option key={a.execution_attempt_id} value={a.execution_attempt_id}>{a.execution_attempt_id.slice(0, 12)} · {a.status}</option>)}</select></label></div><button onClick={()=>void compare()} disabled={!before||!after||before===after} className="mt-4 rounded-lg border border-red-400/20 bg-red-500/10 px-4 py-2 text-xs text-red-200 disabled:opacity-40">Compare selected attempts</button></div>}
    {comparison && <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><div className="glass rounded-2xl p-5"><div className="text-xs uppercase tracking-wider text-zinc-500">Attempt A</div><div className="mt-2 font-mono text-xs break-all">{comparison.before.execution_attempt_id}</div><div className="mt-2 text-sm">{comparison.before.status} · {fmt(comparison.before.started_at)}</div></div><div className="glass rounded-2xl p-5"><div className="text-xs uppercase tracking-wider text-zinc-500">Attempt B</div><div className="mt-2 font-mono text-xs break-all">{comparison.after.execution_attempt_id}</div><div className="mt-2 text-sm">{comparison.after.status} · {fmt(comparison.after.started_at)}</div></div></div>
      <div className="glass rounded-2xl p-5"><div className="font-medium">INTELLIGENCE CHANGE</div><div className="mt-4 grid gap-3 sm:grid-cols-5">{(['added','removed','changed','unchanged','operationally_inconclusive'] as const).map(k=><div key={k} className="rounded-xl border border-white/7 p-4"><div className="text-[10px] uppercase tracking-wider text-zinc-500">{k.replaceAll('_',' ')}</div><div className="mt-2 text-2xl font-semibold">{comparison.intelligence[k].length}</div></div>)}</div></div>
      {comparison.intelligence.operationally_inconclusive.length>0&&<div className="rounded-2xl border border-amber-400/20 bg-amber-500/[.05] p-5"><div className="font-medium text-amber-200">Operationally inconclusive</div><div className="mt-1 text-xs text-amber-200/60">Provider failure, rate limit, unavailable, or skip is not negative intelligence evidence.</div>{comparison.intelligence.operationally_inconclusive.map(i=><div key={i.key.join('|')} className="mt-3 text-sm"><span className="font-mono text-xs">{i.key.join(' · ')}</span> — {i.reason}</div>)}</div>}
      <div className="glass rounded-2xl p-5"><div className="font-medium">OPERATIONAL / PROVIDER CHANGE</div><div className="mt-1 text-xs text-zinc-500">Operational state is shown separately from intelligence.</div><div className="mt-4 space-y-2">{comparison.operational.providers.length?comparison.operational.providers.map(p=><div key={p.provider} className="rounded-xl border border-white/7 p-3 text-sm"><span className="font-medium">{p.provider}</span><span className="ml-2 text-zinc-500">{p.before.join(', ')||'—'} → {p.after.join(', ')||'—'}</span></div>):<div className="text-sm text-zinc-600">No provider operational change.</div>}</div></div>
      <div className="glass rounded-2xl p-5"><div className="font-medium">Risk comparison</div><div className="mt-1 text-xs text-zinc-500">Persisted values only; historical risk is not recomputed.</div><div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded-xl border border-white/7 p-4">Previous score <b className="ml-2">{comparison.risk.previous_score??'—'}</b></div><div className="rounded-xl border border-white/7 p-4">Current score <b className="ml-2">{comparison.risk.current_score??'—'}</b></div><div className="rounded-xl border border-white/7 p-4">Score delta <b className="ml-2">{delta(comparison.risk.score_delta)}</b></div><div className="rounded-xl border border-white/7 p-4">Level <b className="ml-2">{comparison.risk.previous_risk_level||'—'} → {comparison.risk.current_risk_level||'—'}</b></div></div></div>
      <div className="glass rounded-2xl p-5"><div className="font-medium">Provenance</div><div className="mt-2 text-xs text-zinc-500">Investigation #{comparison.investigation_id} · current attempt {comparison.provenance.current_execution_attempt_id||'none'} · identity confirmation: no</div></div>
      <div className="glass overflow-hidden rounded-2xl"><div className="border-b border-white/8 px-5 py-4 font-medium">Evidence changes</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-white/[.025] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-5 py-3">Status</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Source</th><th className="px-5 py-3">Value</th></tr></thead><tbody>{(['added','removed','changed','unchanged'] as const).flatMap(s=>comparison.intelligence[s].map(i=>{const f=i.after||i.before!;return <tr key={`${s}-${i.key.join('|')}`} className="border-t border-white/6"><td className="px-5 py-3 capitalize">{s}</td><td className="px-5 py-3">{f.finding_type}</td><td className="px-5 py-3">{f.source}</td><td className="max-w-xl break-all px-5 py-3">{f.value}</td></tr>}))}</tbody></table></div></div>
    </div>}
  </div>;
}
