from alembic import op
import sqlalchemy as sa
revision='0001'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('investigations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('target',sa.String(320),nullable=False),sa.Column('normalized_email',sa.String(320),nullable=False),sa.Column('username',sa.String(200),nullable=False),sa.Column('domain',sa.String(253),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('risk_score',sa.Integer()),sa.Column('risk_level',sa.String(16)),sa.Column('privacy_mode',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('findings',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('investigation_id',sa.Integer(),sa.ForeignKey('investigations.id',ondelete='CASCADE'),nullable=False),sa.Column('source',sa.String(120),nullable=False),sa.Column('source_url',sa.String(1000)),sa.Column('finding_type',sa.String(120),nullable=False),sa.Column('value',sa.Text(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('severity',sa.String(16),nullable=False),sa.Column('first_seen',sa.DateTime(timezone=True)),sa.Column('last_seen',sa.DateTime(timezone=True)),sa.Column('collected_at',sa.DateTime(timezone=True),nullable=False),sa.Column('raw_reference',sa.JSON()),sa.Column('notes',sa.Text()))
    op.create_table('module_runs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('investigation_id',sa.Integer(),sa.ForeignKey('investigations.id',ondelete='CASCADE'),nullable=False),sa.Column('module',sa.String(80),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('message',sa.String(500)),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('finished_at',sa.DateTime(timezone=True)))
    op.create_table('graph_nodes',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('investigation_id',sa.Integer(),sa.ForeignKey('investigations.id',ondelete='CASCADE'),nullable=False),sa.Column('node_key',sa.String(300),nullable=False),sa.Column('node_type',sa.String(40),nullable=False),sa.Column('label',sa.String(300),nullable=False),sa.Column('node_metadata',sa.JSON()))
    op.create_table('graph_edges',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('investigation_id',sa.Integer(),sa.ForeignKey('investigations.id',ondelete='CASCADE'),nullable=False),sa.Column('source',sa.String(300),nullable=False),sa.Column('target',sa.String(300),nullable=False),sa.Column('relation',sa.String(80),nullable=False),sa.Column('confidence',sa.Float(),nullable=False))

def downgrade():
    for t in ['graph_edges','graph_nodes','module_runs','findings','investigations']: op.drop_table(t)
