/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const */
import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {Finding} from '../src/types';

vi.mock('react',async()=>{
 const actual=await vi.importActual<typeof import('react')>('react');let state:any[]=[];let cursor=0;const effects=new Set<number>();
 return {...actual,useState:<T>(initial:T)=>{const i=cursor++;if(!(i in state))state[i]=initial;return [state[i],(next:T|((v:T)=>T))=>{state[i]=typeof next==='function'?(next as (v:T)=>T)(state[i]):next}] as const},useMemo:<T>(fn:()=>T)=>{cursor++;return fn()},useCallback:<T>(fn:T)=>{cursor++;return fn},useEffect:(fn:()=>void|(()=>void))=>{const i=cursor++;if(!effects.has(i)){effects.add(i);void fn()}},__reset:()=>{state=[];cursor=0;effects.clear()},__rewind:()=>{cursor=0}};
});
vi.mock('../src/services/api',()=>({listInvestigations:vi.fn(),deleteInvestigation:vi.fn(),getInvestigation:vi.fn(),getTimeline:vi.fn(),getGraph:vi.fn(),getCorrelations:vi.fn(),createInvestigation:vi.fn(),downloadReport:vi.fn()}));

const items=[{id:1,target:'alpha@example.com',status:'completed',risk_score:80,risk_level:'high',created_at:'2026-01-02T00:00:00Z'},{id:2,target:'beta@example.com',status:'failed',risk_score:20,risk_level:'low',created_at:'2026-01-03T00:00:00Z'}];
const emailFinding:Finding={id:1,source:'github',finding_type:'email_match',value:'alpha@example.com',confidence:.9,severity:'high',collected_at:'2026-01-01T00:00:00Z',evidence_state:'observed',current_attempt:true,execution_attempt_id:'current',source_url:'https://example.com/evidence',notes:'Observed on public source.'};
const historicalFinding:Finding={id:2,source:'github',finding_type:'email_match',value:'old@example.com',confidence:.6,severity:'medium',collected_at:'2026-01-01T00:00:00Z',evidence_state:'observed',current_attempt:false,execution_attempt_id:'old'};
const dnsFinding:Finding={id:3,source:'dns',finding_type:'mx',value:'mail.example.com',confidence:.8,severity:'info',collected_at:'2026-01-01T00:00:00Z',evidence_state:'observed',current_attempt:true,execution_attempt_id:'current'};
const investigation:any={id:1,target:'alpha@example.com',status:'completed',risk_score:80,risk_level:'high',created_at:'2026-01-02T00:00:00Z',username:'alpha',domain:'example.com',findings:[emailFinding,historicalFinding,dnsFinding,{id:4,source:'github',finding_type:'provider_status',value:'ok',confidence:1,severity:'info',collected_at:'2026-01-01T00:00:00Z',evidence_state:'observed',current_attempt:true,notes:'Provider completed.'},{id:5,source:'risk',finding_type:'risk_dimension',value:'exposure=70',confidence:1,severity:'info',collected_at:'2026-01-01T00:00:00Z',evidence_state:'observed',current_attempt:true}],modules:[{module:'github',status:'completed',message:'Done'}]};
function text(n:any):string{if(n==null||typeof n==='boolean')return '';if(typeof n==='string'||typeof n==='number')return String(n);if(Array.isArray(n))return n.map(text).join('');return text(n.props?.children)}
function elements(n:any):any[]{if(n==null||typeof n!=='object')return [];if(Array.isArray(n))return n.flatMap(elements);return [n,...elements(n.props?.children)]}
function button(tree:any,label:string){return elements(tree).find(e=>e.type==='button'&&text(e)===label)}
function installWindow(){const listeners=new Map<string,Set<() => void>>();(globalThis as any).window={confirm:vi.fn(()=>true),setInterval:vi.fn(()=>1),clearInterval:vi.fn(),addEventListener:(n:string,f:()=>void)=>{if(!listeners.has(n))listeners.set(n,new Set());listeners.get(n)!.add(f)},removeEventListener:(n:string,f:()=>void)=>listeners.get(n)?.delete(f),dispatchEvent:(e:Event)=>{listeners.get(e.type)?.forEach(f=>f());return true}}}
beforeEach(async()=>{vi.clearAllMocks();installWindow();(await import('react') as any).__reset()});

describe('Phase 20 investigation workspace UI',()=>{
 it('covers loading, list rendering, search/filter/sort, open, deletion, empty and error states',async()=>{const api=await import('../src/services/api');vi.mocked(api.listInvestigations).mockResolvedValue(items);vi.mocked(api.deleteInvestigation).mockResolvedValue({id:2,status:'deleted'});const {Investigations}=await import('../src/pages/Investigations');const r=await import('react') as any;r.__rewind();let tree=Investigations({onOpen:vi.fn(),onNew:vi.fn()});expect(text(tree)).toContain('Loading investigations');await Promise.resolve();await Promise.resolve();r.__rewind();tree=Investigations({onOpen:vi.fn(),onNew:vi.fn()});expect(text(tree)).toContain('alpha@example.com');const search=elements(tree).find(e=>e.type==='input'&&e.props['aria-label']==='Search investigations');search.props.onChange({target:{value:'beta'}});r.__rewind();tree=Investigations({onOpen:vi.fn(),onNew:vi.fn()});expect(text(tree)).toContain('beta@example.com');expect(text(tree)).not.toContain('alpha@example.com');const status=elements(tree).find(e=>e.type==='select'&&e.props['aria-label']==='Filter status');status.props.onChange({target:{value:'failed'}});r.__rewind();tree=Investigations({onOpen:vi.fn(),onNew:vi.fn()});expect(text(tree)).toContain('beta@example.com');const sort=elements(tree).find(e=>e.type==='select'&&e.props['aria-label']==='Sort investigations');sort.props.onChange({target:{value:'risk_desc'}});r.__rewind();tree=Investigations({onOpen:vi.fn(),onNew:vi.fn()});expect(text(tree)).toContain('beta@example.com');const row=elements(tree).find(e=>e.type==='tr'&&text(e).includes('beta@example.com'));await elements(row).find(e=>e.type==='button'&&text(e).includes('Delete')).props.onClick();expect(api.deleteInvestigation).toHaveBeenCalledWith(2);const open=vi.fn();r.__reset();r.__rewind();Investigations({onOpen:open,onNew:vi.fn()});await Promise.resolve();await Promise.resolve();r.__rewind();tree=Investigations({onOpen:open,onNew:vi.fn()});const first=elements(tree).find(e=>e.type==='tr'&&text(e).includes('alpha@example.com'));elements(first).find(e=>e.type==='button'&&text(e)==='Open').props.onClick();expect(open).toHaveBeenCalledWith(1);vi.mocked(api.listInvestigations).mockResolvedValue([]);r.__reset();r.__rewind();Investigations({onOpen:vi.fn(),onNew:vi.fn()});await Promise.resolve();await Promise.resolve();r.__rewind();expect(text(Investigations({onOpen:vi.fn(),onNew:vi.fn()}))).toContain('No investigations yet');vi.mocked(api.listInvestigations).mockRejectedValue(new Error('load failed'));r.__reset();r.__rewind();Investigations({onOpen:vi.fn(),onNew:vi.fn()});await Promise.resolve();await Promise.resolve();r.__rewind();expect(text(Investigations({onOpen:vi.fn(),onNew:vi.fn()}))).toContain('load failed')});
});

describe('Phase 20 detail/evidence UI',()=>{
 it('renders detail workspace, all sections, finding provenance, and current/historical evidence',async()=>{const api=await import('../src/services/api');vi.mocked(api.getInvestigation).mockResolvedValue(investigation);vi.mocked(api.getTimeline).mockResolvedValue([] as any);vi.mocked(api.getGraph).mockResolvedValue({nodes:[],edges:[]} as any);vi.mocked(api.getCorrelations).mockResolvedValue({relationships:[],conflicts:[]} as any);const {Investigation}=await import('../src/pages/Investigation');const r=await import('react') as any;r.__reset();r.__rewind();let tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});expect(text(tree)).toContain('Loading investigation #1');await Promise.resolve();await Promise.resolve();r.__rewind();tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});for(const tab of ['Overview','Evidence','Providers','Timeline','Graph','Reports'])expect(text(tree)).toContain(tab);expect(text(tree)).toContain('alpha@example.com');expect(text(tree)).toContain('Execution modules');});
 it('exercises EvidenceExplorer selection, provenance, current/historical filters, and email-only pivot affordance',async()=>{const {EvidenceExplorer}=await import('../src/components/EvidenceExplorer');const r=await import('react') as any;const pivot=vi.fn();r.__reset();r.__rewind();let tree=EvidenceExplorer({findings:[emailFinding,historicalFinding,dnsFinding],onPivot:pivot});expect(text(tree)).toContain('Current execution');expect(text(tree)).toContain('Historical execution');let row=elements(tree).find(e=>e.type==='tr'&&text(e).includes('alpha@example.com'));row.props.onClick();r.__rewind();tree=EvidenceExplorer({findings:[emailFinding,historicalFinding,dnsFinding],onPivot:pivot});expect(text(tree)).toContain('Finding detail');expect(text(tree)).toContain('Observed on public source.');expect(text(tree)).toContain('current');const p=button(tree,'Pivot to separate investigation');expect(p.props.disabled).toBe(false);p.props.onClick();expect(pivot).toHaveBeenCalledWith(emailFinding);row=elements(tree).find(e=>e.type==='tr'&&elements(e).some(child=>child.type==='td'&&text(child)==='mail.example.com'));row.props.onClick();r.__rewind();tree=EvidenceExplorer({findings:[emailFinding,historicalFinding,dnsFinding],onPivot:pivot});expect(button(tree,'Pivot to separate investigation').props.disabled).toBe(true)});
});

describe('Phase 20 provider/execution/report/auth UI',()=>{
 it('renders every execution and provider state and explicitly separates provider failures from intelligence',async()=>{const {ExecutionStatus}=await import('../src/components/ExecutionStatus');for(const s of ['queued','running','completed','failed','abandoned','recovered'])expect(text(ExecutionStatus({status:s}))).toContain(s);const {ProviderStatusGrid}=await import('../src/components/ProviderStatusGrid');const fs=['ok','unconfigured','rate_limited','unavailable','error','disabled'].map((value,i)=>({...dnsFinding,id:20+i,source:`provider-${value}`,finding_type:'provider_status',value}));const tree=ProviderStatusGrid({findings:fs});for(const s of ['ok','unconfigured','rate_limited','unavailable','error','disabled'])expect(text(tree)).toContain(s);expect(text(tree)).toContain('provider failure is not a negative result')});
 it('invokes existing report API actions and handles authentication-required event',async()=>{const api=await import('../src/services/api');vi.mocked(api.getInvestigation).mockResolvedValue(investigation);vi.mocked(api.getTimeline).mockResolvedValue([] as any);vi.mocked(api.getGraph).mockResolvedValue({nodes:[],edges:[]} as any);vi.mocked(api.getCorrelations).mockResolvedValue({relationships:[],conflicts:[]} as any);vi.mocked(api.downloadReport).mockResolvedValue(undefined);const {Investigation}=await import('../src/pages/Investigation');const r=await import('react') as any;r.__reset();r.__rewind();let tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});await Promise.resolve();await Promise.resolve();r.__rewind();tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});const reports=elements(tree).find(e=>e.type==='button'&&text(e)==='Reports');reports.props.onClick();r.__rewind();tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});for(const f of ['JSON','CSV','HTML','PDF'])expect(text(tree)).toContain(`Export ${f}`);await button(tree,'Export JSON').props.onClick();expect(api.downloadReport).toHaveBeenCalledWith(1,'json');window.dispatchEvent(new Event('mailrecon:auth-required'));r.__rewind();tree=Investigation({id:1,onBack:vi.fn(),onOpen:vi.fn()});expect(text(tree)).toContain('Authentication required. Enter your MailRecon API key before continuing.')});
});
