import {useCallback,useEffect,useMemo,useState} from 'react';
import {AlertCircle,FolderSearch,GitCompareArrows,LoaderCircle,Plus,RefreshCw} from 'lucide-react';
import {deleteInvestigation,listInvestigations} from '../services/api';
import type {InvestigationSummary,SortKey} from '../services/workspace';
import {filterInvestigations,sortInvestigations} from '../services/workspace';
import {Badge} from '../components/Badge';

function riskTone(level:string|null){return level==='high'||level==='critical'?'danger':level==='medium'?'warn':level==='low'?'good':'neutral'}

export function Investigations({onOpen,onNew,onCompare}:{onOpen:(id:number)=>void;onNew:()=>void;onCompare:()=>void}){
 const [items,setItems]=useState<InvestigationSummary[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [risk,setRisk]=useState('all'); const [sort,setSort]=useState<SortKey>('created_desc'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [deleting,setDeleting]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await listInvestigations())}catch(e){setError(e instanceof Error?e.message:'Unable to load investigations')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>sortInvestigations(filterInvestigations(items,query,status,risk),sort),[items,query,status,risk,sort]);
 async function remove(id:number){if(!window.confirm(`Permanently delete investigation #${id} and all stored investigation data? This cannot be undone.`))return;setDeleting(id);setError('');try{const result=await deleteInvestigation(id);if(result.status!=='deleted')throw new Error('Unexpected deletion response.');setItems(current=>current.filter(item=>item.id!==id))}catch(e){setError(e instanceof Error?e.message:'Deletion failed')}finally{setDeleting(null)}}
 const statuses=Array.from(new Set(items.map(x=>x.status))).sort();
 const risks=Array.from(new Set(items.map(x=>x.risk_level||'unknown'))).sort();
 return <div className="mx-auto max-w-[1500px] space-y-6 p-5 lg:p-8">
  <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-xs font-medium uppercase tracking-[.22em] text-red-400">Investigation workspace</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Investigations</h1><p className="mt-2 max-w-3xl text-sm text-zinc-500">Navigate persisted investigations, inspect evidence, compare runs, and make explicit analyst pivots without merging identities.</p></div><div className="flex flex-wrap gap-2"><button onClick={onCompare} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/[.05]"><GitCompareArrows size={17}/> Compare</button><button onClick={onNew} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-500 px-4 py-2.5 text-sm font-semibold hover:bg-red-400"><Plus size={17}/> New investigation</button></div></div>
  <div className="glass rounded-2xl p-4"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]"><input aria-label="Search investigations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search target or investigation ID…" className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm outline-none"/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#101010] px-3 py-3 text-sm"><option value="all">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter risk" value={risk} onChange={e=>setRisk(e.target.value)} className="rounded-xl border border-white/10 bg-[#101010] px-3 py-3 text-sm"><option value="all">All risk</option>{risks.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort investigations" value={sort} onChange={e=>setSort(e.target.value as SortKey)} className="rounded-xl border border-white/10 bg-[#101010] px-3 py-3 text-sm"><option value="created_desc">Newest first</option><option value="created_asc">Oldest first</option><option value="risk_desc">Risk: high to low</option><option value="risk_asc">Risk: low to high</option><option value="target_asc">Target A–Z</option></select></div></div>
  {error&&<div role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300"><div className="flex items-center gap-2"><AlertCircle size={16}/>{error}</div></div>}
  {loading?<div className="glass rounded-2xl p-10 text-center text-sm text-zinc-500"><LoaderCircle className="mx-auto mb-3 animate-spin" size={22}/>Loading investigations…</div>:visible.length===0?<div className="glass rounded-2xl p-12 text-center"><FolderSearch className="mx-auto text-zinc-600" size={30}/><div className="mt-3 font-medium">{items.length?'No matching investigations':'No investigations yet'}</div><p className="mt-1 text-sm text-zinc-500">{items.length?'Adjust the search or filters.':'Start an investigation to build your evidence workspace.'}</p>{!items.length&&<button onClick={onNew} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/[.05]"><Plus size={16}/> Start investigation</button>}</div>:<div className="overflow-hidden rounded-2xl border border-white/8 bg-[#0c0c0c]"><div className="flex items-center justify-between border-b border-white/8 px-5 py-4"><div className="font-medium">{visible.length} investigation{visible.length===1?'':'s'}</div><button onClick={load} className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/[.05]"><RefreshCw size={13}/> Refresh</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-white/[.025] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-5 py-3">ID</th><th className="px-5 py-3">Target</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Risk</th><th className="px-5 py-3">Created</th><th className="px-5 py-3"/></tr></thead><tbody>{visible.map(item=><tr key={item.id} className="border-t border-white/6 hover:bg-white/[.02]"><td className="px-5 py-4 text-zinc-500">#{item.id}</td><td className="px-5 py-4 font-medium">{item.target}</td><td className="px-5 py-4"><Badge tone={item.status==='completed'?'good':item.status==='failed'?'danger':'warn'}>{item.status}</Badge></td><td className="px-5 py-4">{item.risk_score===null?<span className="text-zinc-600">—</span>:<div className="flex items-center gap-2"><span>{Math.round(item.risk_score)}</span><Badge tone={riskTone(item.risk_level)}>{item.risk_level||'unknown'}</Badge></div>}</td><td className="px-5 py-4 text-zinc-500">{new Date(item.created_at).toLocaleString()}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>onOpen(item.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/[.05]">Open</button><button onClick={()=>remove(item.id)} disabled={deleting===item.id} className="rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-300 hover:bg-red-500/10 disabled:opacity-50">{deleting===item.id?'Deleting…':'Delete'}</button></div></td></tr>)}</tbody></table></div></div>}
 </div>
}
