import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,LoaderCircle,Mail,LockKeyhole,Download,Globe2} from 'lucide-react';
import {createInvestigation,getApiKey,getInvestigation,getTimeline,downloadReport,setApiKey} from '../services/api';
import type {Investigation,TimelineEvent} from '../types';
import {RiskCard} from '../components/RiskCard';
import {RiskDimensions} from '../components/RiskDimensions';
import {Graph} from './Graph';
import {FindingsTable} from '../components/FindingsTable';
import {Badge} from '../components/Badge';
import {Timeline} from '../components/Timeline';

export function Lookup({onGraph}:{onGraph:(id:number)=>void}){
 const [email,setEmail]=useState('demo@fictional.test'); const [privacy,setPrivacy]=useState(false); const [externalDisclosure,setExternalDisclosure]=useState(true); const [inv,setInv]=useState<Investigation|null>(null); const [timeline,setTimeline]=useState<TimelineEvent[]>([]); const [busy,setBusy]=useState(false); const [err,setErr]=useState(''); const [apiKey,setApiKeyState]=useState(getApiKey()); const [savingKey,setSavingKey]=useState(false);
 useEffect(()=>{const onAuth=()=>{setApiKeyState('');setErr('Authentication required. Enter your MailRecon API key.');};window.addEventListener('mailrecon:auth-required',onAuth);return()=>window.removeEventListener('mailrecon:auth-required',onAuth)},[]);
 function saveKey(){setApiKey(apiKey);setSavingKey(false);setErr('API key saved locally.');}
 async function run(){setBusy(true);setErr('');setInv(null);setTimeline([]);try{const x=await createInvestigation(email,privacy,externalDisclosure);let done=false;let attempts=0;while(!done&&attempts<180){const data=await getInvestigation(x.id);setInv(data);done=['completed','failed'].includes(data.status);attempts++;if(!done)await new Promise(r=>setTimeout(r,700))}if(!done)throw new Error('Investigation exceeded the client polling window. It may still be running.');setTimeline(await getTimeline(x.id));}catch(e){setErr(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 async function exportReport(format:string){if(!inv)return;try{await downloadReport(inv.id,format)}catch(e){setErr(e instanceof Error?e.message:'Report export failed')}}
 const progress=inv?.modules||[]; const dimensions=Object.fromEntries((inv?.findings||[]).filter(f=>f.finding_type==='risk_dimension').map(f=>{const [k,v]=f.value.split('=');return [k,Number(v)]})); const providerStates=(inv?.findings||[]).filter(f=>f.finding_type==='provider_status');
 return <div className="mx-auto max-w-[1500px] space-y-6 p-5 lg:p-8">
  <div><div className="text-xs font-medium uppercase tracking-[.22em] text-red-400">Email investigation</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Turn an email into an evidence map.</h1><p className="mt-2 max-w-3xl text-sm text-zinc-500">Local-first defensive OSINT. Public data, legitimate APIs, transparent confidence, and explainable risk.</p></div>
  <div className="glass rounded-2xl p-4"><div className="flex items-center gap-2"><LockKeyhole size={16} className="text-red-400"/><div className="font-medium">API access</div></div><p className="mt-1 text-xs text-zinc-500">Enter the API key configured in your MailRecon backend. It is stored only in this browser's session storage and cleared when the browser session ends.</p><div className="mt-3 flex flex-col gap-2 md:flex-row"><input aria-label="MailRecon API key" type="password" value={apiKey} onChange={e=>setApiKeyState(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')saveKey()}} placeholder="MAILRECON_API_KEY" className="flex-1 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 font-mono text-sm outline-none"/><button onClick={saveKey} disabled={!apiKey.trim()} className="rounded-xl border border-white/10 px-5 py-3 text-sm font-medium hover:bg-white/[.05] disabled:opacity-40">{savingKey?'Saved':'Save key'}</button></div></div>
  <div className="glass rounded-2xl p-2"><div className="flex flex-col gap-2 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl bg-white/[.035] px-4"><Mail size={18} className="text-zinc-500"/><input aria-label="Email address" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!busy)run()}} className="w-full bg-transparent py-4 outline-none placeholder:text-zinc-600" placeholder="target@example.com"/></div><button disabled={busy} onClick={run} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-500 px-6 py-3 font-semibold text-white transition hover:bg-red-400 disabled:opacity-50">{busy?<LoaderCircle className="animate-spin" size={18}/>:<ArrowRight size={18}/>} {busy?'Investigating…':'Start investigation'}</button></div><div className="grid gap-2 px-3 py-3 text-xs text-zinc-500 md:grid-cols-2"><label className="flex cursor-pointer items-start gap-2"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} className="mt-0.5"/><span><span className="inline-flex items-center gap-1 font-medium text-zinc-400"><LockKeyhole size={13}/> Privacy mode</span> — minimize persisted provider payloads; the target remains stored for continuity. This does not prevent external providers from receiving the target.</span></label><label className="flex cursor-pointer items-start gap-2"><input type="checkbox" checked={externalDisclosure} onChange={e=>setExternalDisclosure(e.target.checked)} className="mt-0.5"/><span><span className="inline-flex items-center gap-1 font-medium text-zinc-400"><Globe2 size={13}/> Allow external-provider disclosure</span> — when enabled, approved public providers may receive the investigation target for their normal OSINT queries. Turn this off to prevent public external-provider queries; it is separate from Privacy Mode.</span></label></div></div>
  {err&&<div role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{err}</div>}
  {inv&&<>
   <div className="grid gap-4 md:grid-cols-4"><div className="glass rounded-2xl p-5"><div className="text-xs text-zinc-500">Target</div><div className="mt-2 truncate font-medium">{inv.target}</div></div><div className="glass rounded-2xl p-5"><div className="text-xs text-zinc-500">Username</div><div className="mt-2 font-medium">{inv.username||'—'}</div></div><div className="glass rounded-2xl p-5"><div className="text-xs text-zinc-500">Domain</div><div className="mt-2 font-medium">{inv.domain}</div></div><RiskCard score={inv.risk_score} level={inv.risk_level}/></div>
   <div className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><div><div className="font-medium">Investigation pipeline</div><div className="text-xs text-zinc-500">Live backend module status</div></div><Badge tone={inv.status==='completed'?'good':inv.status==='failed'?'danger':'warn'}>{inv.status}</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{progress.map(m=><div key={m.module} className="flex items-center gap-3 rounded-xl border border-white/6 bg-white/[.02] p-3 text-sm"><span>{m.status==='completed'?<CheckCircle2 size={16} className="text-emerald-400"/>:m.status==='running'?<LoaderCircle size={16} className="animate-spin text-red-400"/>:<span className="h-4 w-4 rounded-full border border-white/15"/>}</span><div><div className="capitalize">{m.module.replaceAll('_',' ')}</div><div className="text-xs text-zinc-600">{m.message||m.status}</div></div></div>)}</div></div>
   <RiskDimensions dimensions={dimensions}/>
   <div className="glass rounded-2xl p-5"><div className="font-medium">Provider execution</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{providerStates.map(f=><div key={f.source} className="flex items-center justify-between rounded-xl border border-white/7 bg-white/[.02] p-3"><div><div className="text-sm">{f.source}</div><div className="text-xs text-zinc-600">{f.notes}</div></div><Badge tone={f.value==='ok'?'good':f.value==='unconfigured'||f.value==='not_configured'?'warn':'danger'}>{f.value}</Badge></div>)}</div></div>
   <FindingsTable findings={inv.findings}/>
   <Timeline events={timeline}/>
   <div className="glass overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-white/8 px-5 py-4"><div><div className="font-medium">Relationship graph</div><div className="text-xs text-zinc-500">Evidence-backed relationships; possible profiles remain probabilistic.</div></div><button onClick={()=>onGraph(inv.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/[.05]">Open full graph</button></div><div className="h-[480px]"><Graph id={inv.id}/></div></div>
   <div className="glass rounded-2xl p-5"><div className="flex items-center gap-2"><Download size={17} className="text-red-400"/><div><div className="font-medium">Report exports</div><div className="text-xs text-zinc-500">Generate evidence-preserving reports from the API.</div></div></div><div className="mt-4 flex flex-wrap gap-2">{['json','csv','html','pdf'].map(fmt=><button key={fmt} onClick={()=>exportReport(fmt)} className="rounded-lg border border-white/10 bg-white/[.03] px-4 py-2 text-sm hover:bg-white/[.06]">Export {fmt.toUpperCase()}</button>)}</div></div>
  </>}
 </div>
}
